# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

SOURCE := lib-common/FLOAT.c

$(FLOAT_OBJ) :
	mkdir -p obj/lib-common
	$(CC) $(CFLAGS) -m32 -fno-builtin -I/lib-common/ -o $(FLOAT_OBJ) $(SOURCE)